module.exports = {
  "globDirectory": "www/",
  "globPatterns": [
    "assets/fonts/*.woff2",
    "assets/fonts/*.eot",
    "assets/fonts/*.woff2.gz",
    "assets/fonts/*.eot.gz",
    "assets/css/*.css",
    "assets/css/*.css.gz",
    "assets/icon/*.webp",
    "assets/icon/*.webp.gz",
    "assets/icon/*.jpg",
    "assets/icon/*.jpg.gz",
    "assets/icon/*.png",
    "assets/icon/*.png.gz",
    "assets/img/**/*.webp",
    "assets/img/**/*.webp.gz",
    "assets/img/**/*.png",
    "assets/img/**/*.png.gz",
    "assets/img/**/*.jpg",
    "assets/img/**/*.jpg.gz",
    "assets/i18n/*.json",
    "assets/i18n/*.json.gz",
    "build/**/*.css",
    "build/**/*.css.gz",
    "build/**/*.js",
    "build/**/*.js.gz",
    "index.html",
    "manifest.json"
  ],
  "dontCacheBustUrlsMatching": new RegExp('.+\.[a-f0-9]{8}\..+'),
  "maximumFileSizeToCacheInBytes": 12000000,
  "swSrc": "src/service-worker.js",
  "swDest": "www/service-worker.js"
};
